pub fn demonstrate_recoverable_errors() {
    println!("inside demonstrate recoverable errors");
}
